project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
#    - "!slides/"
  resources:
#    - "slides/"
    - "data/"
execute:
  freeze: auto
website:
  google-analytics: G-6LLMGL3T2Q
  title: "BIO8940 course"
#  margin-header: "![](/img/logo_hex.png){width='100px'}"
  description: "Adv stats and open science"
  favicon: /img/logo_hex.png
  navbar:
    title: '![](/img/logo_hex.png){width="50px"} BIO8940: course' 
    left:
      - text: Biostats uOttawa
        href: https://biostats-uottawa.github.io/
      - text: Intro Biostats & R (BioXx58)
        href: https://biostats-uottawa.github.io/bioxx58/
#      - text: Biostats adv. / av.(Bio8940)
#        href: https://biostats-uottawa.github.io/bio8940_course/
      - text: Livre / Book
        menu:
          - text: R-way to hell
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R
            href: https://biostats-uottawa.github.io/R/fr/
    tools:
      - icon: github
        menu:
        - text: Code
          href: https://github.com/biostats-uOttawa/bio8940_course
        - text: Issues
          href: https://github.com/Biostats-uOttawa/bio8940_course/issues
  sidebar:
    - id: fr
      title: "Français"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - icon: flag
          text: English
          href: en/index.qmd
        - text: Info générale
          href: fr/index.qmd
        - text: Diapos et notes
          href: fr/lectures.qmd
        - fr/syllabus.qmd
        - icon: envelope
          text: Contact
          href: fr/people.qmd
    - id: en
      title: "English"
      style: "floating"
      collapse-level: 2
      contents:
        - icon: flag
          text: Français
          href: fr/index.qmd
        - text: Course info
          href: en/index.qmd
        - text: Slides and notes
          href: en/lectures.qmd
        - text: Practical
          href: en/practical.qmd
        - section: Assessment
          contents:
            - en/presentation.qmd
            - en/report.qmd
        - en/dataset.qmd
        - en/syllabus.qmd
        - icon: envelope
          text: "Contact"
          href: en/people.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: css/biostat.css
    toc: true

bibliography: [bio8940_zot.bib]
biblio-style: apalike
csl: ecology.csl
