project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
#    - "!slides/"
  resources:
    - "slides/"
    - "data/"
execute:
  freeze: auto
website:
  google-analytics: G-6LLMGL3T2Q
  title: "BIO8940 course"
  description: "Adv stats and open science"
  navbar:
    title: "BIO8940: course"
    left:
      - text: Lectures
        href: lectures.qmd
      - text: "Practicals"
        menu:
          - text: "Manual"
            href:  https://biostats-uottawa.github.io/bio8940_manual/
          - text: "Data"
            href: dataset.qmd
          - text: "Extra info"
            href: practical_extra.qmd
      - text: "Syllabus"
        href: syllabus.qmd
#      - text: Reading
#        href: reading.qmd
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Bio4158 (english)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Bio4558 (français)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: R-way to hell
            href: https://biostats-uottawa.github.io/intro_r_en.html 
          - text: Chemin de l'enf-R
            href: https://biostats-uottawa.github.io/intro_r_fr.html
    tools:
      - icon: envelope
        href: people.html
        text: Contact
      - icon: github
        menu:
        - text: Code
          href: https://github.com/biostats-uOttawa/bio8940_course
        - text: Issues
          href: https://github.com/Biostats-uOttawa/bio8940_course/issues

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: css/styles.css
    toc: true

bibliography: [bio8940_zot.bib]
biblio-style: apalike
csl: ecology.csl
