---
title: "Lectures"
---

{{< include _links.qmd >}}

```{r}
#| echo: false
#| include: false
knitr::opts_chunk$set(echo = FALSE)
source("_yaml_extract.R")
library(gt)
library(lubridate)
```


<!-- ### Lecturer {{< fa person-chalkboard >}}  -->

```{r lecturers, results="asis", eval = FALSE, include = FALSE}
team_df %>%
  filter(role == "lecturer") %>%
  pull(name) %>%
  ui_list()
```

<!-- ## Teaching assitant`r ifelse(ntutor > 1, 's', '')`-->
```{r tutors, results="asis"}
team_df %>%
  filter(role == "tutor") %>%
  pull(name) %>%
  ui_list()
```
<!-- 
### Office hours {{< fa clock >}}

Meetings will be in-person or online using zoom. Check brightspace for the links. -->

```{r consult, results="asis", eval = FALSE, include = FALSE}
team_df %>%
  mutate(consult_print = glue::glue("**{name}**: {consult}")) %>%
  pull(consult_print) %>%
  ui_list()
```

### Schedule {{< fa calendar-days >}}

```{r timetable, results="asis"}
timetable_df %>%
  mutate(timetable = glue::glue("**{class}**: {when} in {where}")) %>%
  pull(timetable) %>%
  ui_list()
```

There are no lectures or tutorials during reading week.

```{r}
check <- character(0)
schedule_df <- schedule_df %>%
  rowwise() %>%
  mutate(
    lecture_file = ifelse(
      identical(
        str_subset(
          list.files("slides/", pattern = "slides.html", full.names = TRUE),
          pattern = sprintf("lec-%.2d", week)
        ),
        check
      ),
      NA,
      str_subset(
        list.files("slides/", pattern = "slides.html", full.names = TRUE),
        pattern = sprintf("lec-%.2d", week)
      )
    ),
    notes_file =  ifelse(
      identical(
        str_subset(
          list.files("slides/", pattern = "notes", full.names = TRUE),
          pattern = sprintf("lec-%.2d", week)
        ),
        check
      ),
      NA,
      str_subset(
        list.files("slides/", pattern = "notes", full.names = TRUE),
        pattern = sprintf("lec-%.2d", week)
      )
    ),
    lecture = !is.na(lecture_file)
  ) %>%
  ungroup() %>%
  mutate(
    Slides = case_when(
      lecture ~ glue("<a class='fa fa-link' href='{lecture_file}' target='_blank'></a> <a class='fa fa-file-pdf' href='{notes_file}' target='_blank'></a>"),
      TRUE ~ ""
    ),
    Topic = ifelse(is.na(topic), "", topic),
    Assessment = ifelse(is.na(assessment), "", assessment),
    Reading = ifelse(is.na(reading), "", reading),
    Date = as.Date(ifelse(
      (ymd(dat$date_start) + weeks(week-1)) > ymd(dat$date_read),
      ymd(dat$date_start) + weeks(week),
      ymd(dat$date_start) + weeks(week - 1)
    ))
  ) %>%
  select(Date, Topic, Slides, Reading, Assessment)

midsem_break <- 6 # after which week

read_week <- paste0()
schedule_df %>%
  gt() |>
#  cols_label(week = "Week") |>
  fmt_markdown(columns = c("Slides", "Reading")) |>
  fmt_date(
    columns = Date,
    date_style = "MMMd",
    locale = "en"
  ) |>
  tab_row_group(
    label = "Reading week",
    rows = (midsem_break + 1):12
  ) |>
  row_group_order(groups = c(NA, "Reading week")) |>
  cols_width(
    Date ~ px(50),
    Slides ~ px(20)
  )
```




