---
title: "Syllabus"
output:
  html_document:
      toc: false
      toc_float: true
      toc_depth: 2
---

```{r setup, echo = FALSE}
start <- 1430
stop <- 1720
where <- "DMS 3105"
```
# {.tabset }

## English

### Description

Statistics are a key component of rigorous science and as such there is a need to both understand advanced statistics and properly document the analysis to improve scientific communication transparency and quality.
The course aims to:

1. Provide an understanding of advanced statistical models (including generalized linear mixed models)
2. Develop good coding practices (using R and Rmarkdown)
3. Improve data and code management (data manipulation and github)
4. Present the principles of open science (using OSF, Open Science Framework).


### Contents

* Statistics (flexible to be define based on attendance interests)
    * Mixed models including generalized linear mixed models and multivariate models
    * Options:
      * Introduction to Bayesian stats
      * Path analysis
      * Spatial analysis
      * Multivariate analysis
      * ...
* Open and reproducible science
    * R: `Rmarkdown`, `tidyverse` and `workflowr`
    * git: `github` and other alternatives
    * Open Science Framework with `OSF`

### Classes

* Duration: 1 class of 3h each week
* Style: mix of lecture, discussion and practical
* How: In-person . 
* When: Tuedays from `r start` to `r stop`
* Where:
  * Room: `r where`
<!--   * Gather: https://gather.town/app/MCa0j7kcdaCNSCvS/AdvStatOpenSci
  * Zoom: https://uottawa-ca.zoom.us/j/93306840602?pwd=bWNsR3AzQ25VQXJOWCszNmh6RWI1UT09 -->
  * Course info and slides: https://biostats-uottawa.github.io/bio8940_course/
  * Lab manual: https://biostats-uottawa.github.io/bio8940_manual/



### Assessment

Based on interactions in classes and on a data analysis project using `R` and documented with with `Rmarkdown`, `workflowr` and `github`.

* 50% in class assessment:
  * 15 min presentation in small groups on a paper and questions (10% content, 10% delivery, 10% answers questions)
  * discussion in class (10% questions prep, 10% discussions)
* 50% written statistical report using analysis more complex than linear models written using Rmarkdown, published on github in 2 different formats

#### Presentation

##### Content – 10%

- Introduction: Background of the general ‘big picture’ and specific problem, study system, and specific hypotheses or predictions.
- Methods: Brief outline of data collection  and explanation of statistical methods used to address the hypotheses/predictions outlined in the introduction, including key assumptions.
- Results: Visualizations clearly summarizing your results, using parallel structure to methods
- Discussion: Summary of major results, alternative explanations for the observed results, conclusions/implications, future directions

##### Style – 10%

- Organization 
- Clarity 
- Delivery: Timing, pace, tone, articulation
<!-- - Originality: (5 marks) Creativity, critical thinking -->

##### Answers and understanding – 10%

#### Written report

##### Content – 70%

- Introduction: (10 marks) Background of the general ‘big picture’ and specific problem, study system, and specific hypotheses or predictions.
- Methods: (20 marks) Brief outline of data collection  and explanation of statistical methods used to address the hypotheses/predictions outlined in the introduction, including key assumptions.
- Results: (25 marks) Visualizations clearly summarizing your results, using parallel structure to methods
- Discussion: (15 marks) Summary of major results, alternative explanations for the observed results, conclusions/implications, future directions

##### Style – 30%

- Clarity and reproducibility of code (10 marks)
- Organization (5 marks)
- Clarity of text (10 marks)
- Typos and grammar (5 marks)
<!-- - Delivery: (5 marks) Timing, pace, tone, articulation -->
<!-- - Originality: (5 marks) Creativity, critical thinking -->


### Schedule

This is a tentative schedule.

| Week | Subject |
|------|---------|
|  1 | Intro and discussion on Stats and science |
|  2 | Rmarkdown and importance of reproducibility |
|  3 | Recap on linear models |
|  4 | Generalized linear models |
|  5 | Linear mixed models (including random slopes) |
|  6 | Generalized linear mixed models (and intro to gamms) |
|  7 | Reading week |
|  8 | Intro to Bayesian stats |
|  9 | Complex mixed models (spatial, temporal autocorrelation, non-independence random effects) |
| 10 | PCA and ordinance analysis |
| 11 | Multivariate mixed models |
| 12 | Path analysis and causality |
| 13 | Wrap-up |

### Note on bilingualism

Please note that the class is bilingual. This means that any questions during the class can be asked or answered in either french or english and the prof will translate the answers if needs be. The majority of the course content (slides, lab manual) are provided in english only, but explanation can be provided in either languages.

## Français

### Description et objectifs

Les analyses statistiques sont fondamentales à un processus scientifique rigoureux. Par conséquent, il est primordiale de comprendre les statistiques et de reporter correctement les analyses pour améliorer la transparence et la qualité de la science.
Les objectifs du cours sont:

1. Améliorer la compréhension des modèles statistique avancés (incluant les modèles mixtes généralisés)
2. Développer de bonnes habitudes pour coder (utilisation de R et Rmarkdown)
3. Améliorer la gestion des données et du code statistique (manipulation de données et github)
4. Présenter les principes de science ouverte (se basant sur OSF, Open Science Framework)


### Contenu

* Statistiques (contenu flexible à définir en fonction de l'intérêt des participants)
  * Modèles linéaires généralisés
  * Modèles linéaires mixtes (généralisés et multivariés)
  * sujets flexibles:
    * Introduction aux stats Bayesienne
    * Analyse de piste
    * analyse spatiale
    * analyse multivariée
    * analyse en composante principale
    * GAM et GAMMs
    * ...
* Science ouverte répétable
  * R: `Rmarkdown`, `tidyverse`, et `workflowr`
  * git: `github` et autre alternative
  * Open Science framework avec `OSF`

### Cours

* Durée: 1 cours de 3h par semaine
* Style: mélange de  cours, discussion et labo
* Comment: Session Zoom interactive avec tous les participants
* Quand: Mardis `r start` à `r stop`
* Où:
  * Salle: `r where`
<!--   * Gather: https://gather.town/app/MCa0j7kcdaCNSCvS/AdvStatOpenSci
  * Zoom: https://uottawa-ca.zoom.us/j/93306840602?pwd=bWNsR3AzQ25VQXJOWCszNmh6RWI1UT09 -->
  * Course info and slides: https://biostats-uottawa.github.io/bio8940_course/
  * Lab manual: https://biostats-uottawa.github.io/bio8940_manual/



### Évaluation

L'évaluation sera basée sur la participation et sur la réalisation d'un projet qui analysera des données en utilisant `R` et documentera l'analyse avec `Rmarkdown`, `workflowr` et `github`.

* 50% évaluation en classe:
  * 15 min présentation en petit groupes sur un article choisi par les étudiants
  * discussion en classe (10% questions, 10% discussions)
* 50% travail de session présentant une analyse statistique vu en cours (ou plus complexes), rédigé avec Rmardown et publiées sur github

#### Présentation

##### Contenu – 10%

- Introduction: Contexte général, hypothèses et prédictions spécifiques à l'étude.
- Méthodes: Brève description de la collecte des données. Explication des analyses statistiques à la lumière des hypothèses et ou prédictions
- Results: Représentation des clair des résultats
- Discussion: Explications des résultats, limite de l'étude? critique des analyses par rapport aux données et aux hypothèses

##### Style – 10%

- Organisation 
- Clarté 
- Style: Temps, vitesse, rhytme, ton de la voix, interactions avec audience
<!-- - Originality: (5 marks) Creativity, critical thinking -->

##### Réponse et compréhension – 10%

#### Travail de session

##### Content – 60%

- Introduction: (10 marks) Contexte général, hypothèses et prédictions spécifiques à l'étude.
- Methods: (20 marks) Brève description de la collecte des données. Explication des analyses statistiques à la lumière des hypothèses et ou prédictions
- Results: (20 marks) Représentation des clair (incluants graphiques) des résultats
- Discussion: (10 marks) Explications des résultats, limite de l'étude? critique des analyses par rapport aux données et aux hypothèses

##### Style – 40%

- Clarté et reproducibilité du code (20 marks)
- Organisation (5 marks)
- Clarté du texte (10 marks)
- Orthographe et grammaire (5 marks)
<!-- - Delivery: (5 marks) Timing, pace, tone, articulation -->
<!-- - Originality: (5 marks) Creativity, critical thinking -->


### Calendrier


| Semaine | Subject |
|------|---------|
|  1 | Intro and discussion on Stats and science |
|  2 | Rmarkdown and importance of reproducibility |
|  3 | Intro to Github |
|  4 | Generalized linear models |
|  5 | Linear mixed models (including random slopes) |
|  6 | Generalized linear mixed models (and intro to gamms) |
|  7 | Reading week |
|  8 | Intro to Bayesian stats |
|  9 | Complex mixed models (spatial, temporal autocorrelation, non-independence random effects) |
| 10 | PCA and ordinance analysis |
| 11 | Multivariate mixed models |
| 12 | Path analysis and causality |
| 13 | Wrap-up |


### Note sur le bilinguisme

Le cours est un cours bilingue. Cela signifie que l'ensemble des interactions orales peuvent avoir lieu en français ou en anglais, le prof pouvant fournir les traductions nécessaires pour que l'ensemble des étudiants comprennent la matière. Le contenu du cours (diapo et manuel de laboratoire) seront présenté de manière unilingue en anglais avec possibilité de fournir des explanations en français si besoin.

# {-}